services:
  - type: web
    name: phoebe-extractor-api
    env: node
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "npm run start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: TRIDENT_USERNAME
        sync: false
      - key: TRIDENT_PASSWORD
        sync: false
      - key: MYPIN_USERNAME
        sync: false
      - key: MYPIN_PASSWORD
        sync: false
